version: '3.8'

services:
  waserva:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: waserva-dev
    restart: unless-stopped
    ports:
      - "3025:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./sessions:/app/sessions
    env_file:
      - .env
    networks:
      - network_app

networks:
  network_app:
    external: true
