version: '3.8'

services:
  waserva:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./sessions:/app/sessions
    env_file:
      - .env
    networks:
      - network_app

networks:
  network_app:
    external: true
